[package]
edition = "2021"
name = "gtk-nodejs"
version = "0.0.0"

[dependencies]
generation = { path = "generation" }

[workspace]
members = [
  #"repository",
  #"generation",
  #"common",
  #"output"
  "introspection",
  "generation_classic"
]
