[package]
edition = "2021"
name = "introspection"
version = "0.0.0"

[build-dependencies]
bindgen = "0.65.1"
system-deps = "2.0"

[package.metadata.system-deps]
girepo = { name = "gobject-introspection-1.0", version = "1.72.0" }